### PR TITLE
Ability to set cookieName, cookieDomain, cookieExpires

### PR DESCRIPTION
**Pull request by martinssipenko**
This adds ability to set `cookieName`, `cookieDomain`, `cookieExpires` under Advanced Settings of Tracking Code screen.

### CODE REVIEW

**Comment by deconf** [comment]
Looks good, thanks!

**Comment by martinssipenko** [comment]
Any chance this could be released in near future?

**Comment by deconf** [comment]
It will, before 2015-12-08 (WP 4.4 release date) for sure.

**Comment by martinssipenko** [comment]
Thanks!

**Pull request merged**
