### PR TITLE
Sort Google views response by name field

### PR DESCRIPTION
**Pull request by shawndrake2**
At my company, we have a very long list of property views to choose from. I'd be interested in seeing it sorted in the Views dropdown.

### CODE REVIEW

**Comment by deconf** [comment]
Hi,
Sounds good, but we need to maintain compatibility with PHP 5.2.x, where anonymous functions are not available.

It would be great if you could submit a patch without making use of anonymous functions.

**Comment by shawndrake2** [comment]
Understood, will do. Thanks!

**Comment by deconf** [comment]
You can add the helper function in the GADWP_Tools, as static and just call it where needed.

**Comment by shawndrake2** [comment]
@deconf I'm not sure if you noticed the change, but if you could take a look now and let me know what you think, that would be great.

**Comment by deconf** [comment]
It seems okay, I will have a look as soon as I will get back to the office (Easter vacation).

**Comment by shawndrake2** [comment]
Sounds great, thanks! Happy Easter!

**Comment by deconf** [comment]
Thank you!

**Comment by deconf** [comment]
After some in-depth testing it looks like it's not going to work because the final list is displayed as 

the website url &#8658; the view name

Sorting by the view name will mix properties which is undesirable.

**Comment by shawndrake2** [comment]
Understood, I appreciate the feedback. Any thoughts on how to achieve what we want without forking the master? i.e. configuration options for sorting, etc?

**Pull request merged**
