### PR TITLE
Honor DNT header

### LINKED ISSUE #102: Add an option to respect Do Not Track header
It would be nice to have an opt-in option to respect [Do No Track](https://www.mozilla.org/firefox/dnt/) header. When checked in the admin, the plugin won't include the GA code in the page when the Do Not Track header is sent with the request.

### PR DESCRIPTION
**Pull request by MikkCZ**
fix #102

At the beginning I wanted to use the similar mechanism as for excluding particular roles in `tracking.php`, checking the plugin preference and the DNT header presence and value.
```
// excluded roles
if ( GADWP_Tools::check_roles( $this->gadwp->config->options['track_exclude'], true ) || ( $this->gadwp->config->options['superadmin_tracking'] && current_user_can( 'manage_network' ) ) ) {
	return;
}
```
However for DNT the problem is compatibility with caching plugins. When enabled and caching plugin is installed, the result (with or without GA included) of the first request will be served to everyone, until the cache is refreshed.

For that reason I have split the condition between PHP and JavaScript. In PHP the plugin preference is determined, but DNT is checked in JavaScript. When a caching plugin is installed, you need to wait until the cache is refreshed for the change in preferences to take effect in the output HTML, but then JavaScript truly respects the users choice.

### CODE REVIEW

**Comment by MikkCZ** [comment]
@deconf r?

**Comment by deconf** [comment]
Hi,

Thanks for the PR. The plugin has three components: AMP Tracking, GTM tracking and Web Analytics tracking. To have a fully functional feature we'll have to cover all three cases. I'm not sure about AMP, do mobile versions of Firefox send DNT?

**Comment by MikkCZ** [comment]
DNT should be always opt-in in all browsers. I am not sure about other browsers, but both desktop and Android version of Firefox allow to enable DNT.

**Comment by MikkCZ** [comment]
Hi @deconf . I have added DNT for the tag manager, however I haven't found a way to do that for AMP, as there is no JavaScript code. Doing that server side won't work because of the caching.

**Comment by MikkCZ** [comment]
@deconf r?

**Comment by MikkCZ** [comment]
@deconf Can you please have another look so I know if there is something more needed, or merge this PR?

**Comment by deconf** [comment]
Hi,

Thank you for the pull request, as soon as we find the time and opportunity we're going to implement it.

Our number one priorities right now are: achieve a stable and reliable endpoint (unrelated to this PR), GDPR compliance (related to this), and then enhancements like DNT.

We're talking about a plugin used by over a million of websites, so features have a priority and need to be fully tested.

**Pull request closed without merging**
